export const TABLE_DATA = [
  {
    firstColumn: '项目名称',
    secondColumn: 'projectName',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '类型',
    secondColumn: 'type',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '建设单位',
    secondColumn: 'constructUnit',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '建设地点',
    secondColumn: 'constructAddress',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '建设内容和规模',
    secondColumn: 'constructDetail',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '进度安排',
    secondColumn: 'schedule',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '用地情况（m²）',
    secondColumn: 'landUse',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '是否开工',
    secondColumn: 'isStart',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '是否竣工',
    secondColumn: 'isEnd',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '2022年计划投资（万元）',
    secondColumn: 'planFirst',
    thirdColumn: '其中政府投资（万元）',
    fourthColumn: 'planFirstGov',
    fifth: '其中带动投资（万元）',
    sixth: 'planFirstDrive',
  },
  {
    firstColumn: '2023年计划投资（万元）',
    secondColumn: 'planSecond',
    thirdColumn: '其中政府投资（万元）',
    fourthColumn: 'planSecondGov',
    fifth: '其中带动投资（万元）',
    sixth: 'planSecondDrive',
  },
  {
    firstColumn: '2022年完成投资（万元）',
    secondColumn: 'comFirst',
    thirdColumn: '其中政府投资（万元）',
    fourthColumn: 'comFirstGov',
    fifth: '其中带动投资（万元）',
    sixth: 'comFirstDrive',
  },
  {
    firstColumn: '2023年完成投资（万元）',
    secondColumn: 'comSecond',
    thirdColumn: '其中政府投资（万元）',
    fourthColumn: 'comSecondGov',
    fifth: '其中带动投资（万元）',
    sixth: 'comSecondDrive',
  },
  {
    firstColumn: '计划投资完成率（%）',
    secondColumn: 'planRate',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '年度投资完成率（%）',
    secondColumn: 'yearRate',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: '总体进度（%）',
    secondColumn: 'overallProgress',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
  {
    firstColumn: `本月项目进度情况照片`,
    secondColumn: 'oldPics',
    thirdColumn: '',
    fourthColumn: '',
    fifth: '',
    sixth: '',
  },
];
